### ISSUE TITLE
documentation fixes needed

### ISSUE THREAD

**Issue by ericduran** [NBCUTechnology/pubstack#69]
- [x] vagrant provision comment in the default cofig yaml (#90)
- [x] list the xhprof in the pubstack host alias (#82)
- [x] list all sites available in pubstack index.php (#88)
- [x] list database credentials and connection for user (#88)
- [x] explain xdebug setup on the project page (#89)
- [x] link to new issue from project page, readme, default comfig, etc... (#88)
